import Head from 'next/head'
import { useState } from 'react'
import Card from '../components/Card/Card'
import Filter from '../components/Filter/Filter'
import LoadCardsBtn from '../components/LoadCardsBtn/LoadCardsBtn'

export default function Home() {

  const [isLoad, setIsLoad] = useState(false)

  const loadMore = () => {
    setIsLoad(true)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className="mt-24 mb-5 mx-auto px-4 max-w-screen-lg lg:px-8">
        <div className="text-center max-w-lg mx-auto">
          <h1 className="text-4xl font-semibold">
            Help a student to continue his studies.
          </h1>
          <p className="mt-3 text-gray-500">
            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour,
          </p>
        </div>
        <Filter />
        <ul className="mt-12 space-y-6">
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </ul>
        <div className="mt-7 flex justify-center">
          <LoadCardsBtn
            isLoad={isLoad}
            onClick={loadMore}
          />
        </div>
      </main>
    </>
  )
}
