import Head from 'next/head'
import { useState } from 'react'
import Card from '../components/Card/Card'
import Filter from '../components/Filter/Filter'
import LoadCardsBtn from '../components/LoadCardsBtn/LoadCardsBtn'
import { useRouter } from 'next/router'
import axios from 'axios'
import url from '../url/url'

export default function Home({ posts }) {

  const router = useRouter()

  const [isLoad, setIsLoad] = useState(false)

  const loadMore = () => {
    setIsLoad(true)
  }

  return (
    <>
      <Head>
        <title>Students aids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="mt-24 mb-5 mx-auto px-4 max-w-screen-lg lg:px-8">
        <div className="text-center max-w-xl mx-auto">
          <h1 className="text-4xl font-semibold">
            Help a student to continue his studies.
          </h1>
          <p className="mt-3 text-gray-500">
            Do you want to create a huge impact in the world? So let's build the future, by helping students to fund their needs, and get the mentorship they need in order to take them to the next level.
          </p>
        </div>
        <Filter />
        <ul className="mt-12 space-y-6">
          <Card posts={posts} />
        </ul>
        <div className="mt-7 flex justify-center">
          <LoadCardsBtn
            isLoad={isLoad}
            onClick={loadMore}
          />
        </div>
      </main>
    </>
  )
}


export const getServerSideProps = async () => {

  const { data } = await axios.get(`${url}/api/posts`)

  return {
    props: {
      posts: data.posts
    }
  }
}